typography_spectrum: 1
color:
  brandColors:
    - '#fffffd'
    - '#311512'
    - '#783a2f'
    - '#adc0a2'
    - '#67764e'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.3125
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Herbal Health Collective
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Welcome!
    id: 28c02d22-5395-4da4-a822-88412d9869c6
    type: content
  - name: THE HERB SHOP
    id: df61321f-110b-4d97-aa6b-e90b5a53b062
    type: content
  - name: PRACTITIONER SERVICES
    id: 1f2942e3-4fc0-4926-8298-eaf9f701bfc7
    type: content
  - name: JOIN US!
    id: e470b1c1-ca46-467a-b07d-f8426edb84c4
    type: content
favicon: null
title: Herbal Health Collective
description: Taking You from Hell-ville to Well-ville
purpose: []
