typography_spectrum: 0.2556987798307091
color:
  brandColors:
    - '#EB6E44'
    - '#7C786A'
    - '#D3E397'
    - '#8DCDC1'
    - '#FFF5C3'
  brandStrength: 0.12106446456164122
  lightness: 0.8404311642516404
  saturation: 0.8705218504182994
  rhythmicContrast: 0.5971184398513287
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.010211337357759476
analytics:
  google: null
  facebook: null
  twitter: null
name: Herbal Health Collective
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: JOIN US!
    id: e470b1c1-ca46-467a-b07d-f8426edb84c4
    type: content
  - name: Welcome!
    id: 28c02d22-5395-4da4-a822-88412d9869c6
    type: content
  - name: THE HERB SHOP
    id: df61321f-110b-4d97-aa6b-e90b5a53b062
    type: content
  - name: PRACTITIONER SERVICES
    id: 1f2942e3-4fc0-4926-8298-eaf9f701bfc7
    type: content
  - name: PRACTITIONERS DIRECTORY
    id: 0dc6baab-df30-438f-aeae-322334d2752c
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fd28c3b1-6afa-43e9-a4d4-98756f961292.jpg
title: Herbal Health Collective
description: Taking You from Hell-ville to Well-ville
purpose: []
