name: Herbal Health Collective
favicon: null
layout_spectrum: 0.011487171752378345
typography_spectrum: 0.06520998547784984
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.573689587181434
  lightness: 0.5529397483915091
  saturation: 0.5351244013290852
  rhythmicContrast: 0.19395884685218334
purpose: []
