typography_spectrum: 1
color:
  brandColors:
    - '#fffffd'
    - '#311512'
    - '#783a2f'
    - '#adc0a2'
    - '#67764e'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.3125
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Herbal Health Collective
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Herbal Health Collective
description: Taking You from Hell-ville to Well-ville
purpose: []
